### ISSUE TITLE
Re-deploy the site so that Date() in Footer shows 2023

### ISSUE THREAD

**Issue by abhiram11** [PowerLoom/pooler-docs#5]
Hi,

I was going through Powerloom for Blockchain Engineer and/or Frontend-related roles and found the project and vision of the company quite interesting! This made me check out the website and some documentation at the basic level. I thought of adding this as a Discussion instead of an issue, but Github didn't allow it for this repo for some reason.

I found out that the copyright year at the footer of the `docs site` showed 2022, and thought of updating it via a PR, only to find out that the code was correct, but the re-deployment hasn't been done in 2023.

Also, to further optimize the `powerloom.io` website, we can also use AVIF instead of PNGs and also resize the images (and crop; e.g., divergence ventures logo) for even further optimization!

Let me know if I can assist you guys with anything regarding the above or for any other issue related to Frontend, Solidity, and JavaScript in general! I am relatively a beginner in Blockchain/Solidity but I have done open-source contributions to React, Hardhat, Wagmi, Preact, Lenster, and many other impactful projects!

Have a great weekend!

**Comment by SwaroopH** [comment]
Thanks for flagging this. We're about to push some changes to the docs and hence the hold up on deployment.

Wrt powerloom.io, will take a note. That repo needs some cleanup before going public!

As for contributing, you are welcome to contribute whatever way you can. We just started open sourcing all our code yesterday, watch out for a call to action next week. Meanwhile, you can start tinkering around with the code in other repos :)

**Comment by abhiram11** [comment]
Congratulations on open-sourcing your code! Will be waiting for CTA next week as well, till then let me see if I can provide any assistance to your codebase 👨🏻‍💻

Closing this issue now 😄
